### ISSUE TITLE
Fix bug UI tags with long names

### ISSUE THREAD

**Issue by hughcrt** [llmonitor/llmonitor#54]
![Image](https://github.com/llmonitor/llmonitor/assets/24587702/28b5ff1b-43e9-401f-aa0c-5d0fee006dcf)

**Comment by Dhoni77** [comment]
Hi @vincelwt I would like to work on this issue

**Comment by hughcrt** [comment]
Hi @Dhoni77,
We'd be glad if you could work on that. Let us know if you need any assistance setting up the project.

**Comment by fitrahfm** [comment]
Hi @hughcrt would love to work on this. May I know how to reproduce this issue?

**Comment by hughcrt** [comment]
Hi @fitrahfm ,
You need to use tags with long names: https://llmonitor.com/docs/features/tags?lang=js
Let me know if you can't reproduce it

**Comment by hughcrt** [comment]
![Image](https://github.com/llmonitor/llmonitor/assets/24587702/e0de4eec-be61-4f19-9b91-111f2c00157f)
