### ISSUE TITLE
Does it support async tracking over CURL?

### ISSUE THREAD

**Issue by flexchar** [llmonitor/llmonitor#58]
I am wondering if this is possible to integrate into existing solutions in PHP.

**Comment by nesben** [comment]
I'm looking for the same, would be great if it's possible!

**Comment by vincelwt** [comment]
Hi @flexchar and @nesben, thanks for opening the issue.

Good idea.

So we do have an endpoint already, but we'd need to clean it up a little and document how to use it. 

Will try to get something in the next week or so!

**Comment by vincelwt** [comment]
Hey @nesben and @flexchar, 

We just published this documentation on how to report events with the HTTP endpoint directly: https://www.llmonitor.com/docs/others

Let me know what you think?

Cheers!
